# render.yaml - Configuración para Render
services:
  - type: web
    name: ml-service
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      - key: PIP_PREFER_BINARY
        value: 1
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: PIP_NO_BUILD_ISOLATION
        value: 1
      - key: SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL
        value: "False"
      - key: SKLEARN_SITE_JOBLIB
        value: "1"
